[package]
authors = ["Effnote <effnote@gmail.com>"]
name = "fchat"
version = "0.1.0"

[dependencies]
reqwest = "0.9.5"
serde = "1.0.11"
serde_derive = "1.0"
serde_json = "1.0.2"
websocket = "0.21.1"

[dev-dependencies]
tokio-core = "0.1.9"

[lib]
