[package]
authors = ["Effnote <effnote@gmail.com>"]
name = "fchat"
version = "0.1.0"

[dependencies]
nom = "3.2.1"
reqwest = "0.7.3"
serde = "1.0.11"
serde_derive = "1.0"
serde_json = "1.0.2"
websocket = "0.20.2"

[dev-dependencies]
tokio-core = "0.1.9"

[lib]
