[package]
name = "fchat"
version = "0.1.0"
authors = ["Effnote <effnote@gmail.com>"]
build = "build.rs"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]

[lib]

[[bin]]
name = "simple_client"

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = { version = "*", optional = true }
hyper = "*"
url = "*"
websocket = "~0.12.2"

[build-dependencies]
serde_codegen = { version = "*", optional = true }
syntex = "*"
