[package]
name = "fchat"
version = "0.1.0"
authors = ["Effnote <effnote@gmail.com>"]

[lib]

[dependencies]
serde = "1.0.11"
serde_json = "1.0.2"
serde_derive = "1.0"
reqwest = "0.7.3"
websocket = "0.20.2"

[dev-dependencies]
tokio-core = "0.1.9"
