[package]
name = "fchat"
version = "0.1.0"
authors = ["Effnote <effnote@gmail.com>"]

[lib]

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
hyper = "*"
url = "*"
websocket = "~0.12.2"
